### ISSUE TITLE
To-do for version 0.1.0

### ISSUE THREAD

**Issue by privet-kitty** [privet-kitty/albert#1]
- [x] Display progress at footer
- [x] Display score at footer
- [ ] ~~Fade the user color in~~ (cancelled)
- [ ] ~~Fade the system color in~~ (cancelled)
- [x] Hue can be specified only by drag
- [x] Write README.md
- [x] index.html contains the absolute link to README.md
- [x] Buttons and sliders become gray when out-of-gamut
- [x] Test CIEDE2000 with the data by Sharma-Wu-Dalal
- [x] Test on Edge
